# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0811aefbab5d0584809bc04f4e098f3474b04464e16f785d9120386c566cf483b73c701f0b383f23e39d37c60b3311f85e24ba7e15f13b04c2572238c290859a

test:
  secret_key_base: 3f2b7f8f248481b4180f1710766c9f5c54d8a34ced458e3432527f9aecf1b6c3b8fe448b20185f520b668fbbbf5b52dafef8a02c391365550ec4c813147f358b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
